import ThemeProviderWrapper from "../theme/ThemeProvider.js";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProviderWrapper>
        <body>{children}</body>
      </ThemeProviderWrapper>
    </html>
  );
}
