import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HelmetProvider>
        <Provider store={store}>
          <SidebarProvider>
            <BrowserRouter>
              <ScrollTop />
              <AuthProvider>{children}</AuthProvider>
            </BrowserRouter>
          </SidebarProvider>
        </Provider>
      </HelmetProvider>
      ,
    </html>
  );
}
